spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  jpa:
    show-sql: ${SHOW_SQL}
  mail:
    enabled: ${MAIL_ENABLED}
    from: ${MAIL_FROM}
    host: ${MAIL_HOST}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL}
  flyway:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: ${PORT}
custom:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    issuer: ${JWT_ISSUER}
  azure:
    blob-storage:
      connection-string: ${BLOB_STORAGE_CONNECTION_STRING}
      container-name: ${BLOB_STORAGE_CONTAINER_NAME}