logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: Boilerplate
  web:
    locale-resolver: accept-header
  mvc:
    locale-resolver: accept-header
    servlet:
      path: /api/v1
  messages:
    encoding: UTF-8
  profiles:
    active: ${PROFILE}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
  mail:
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db.migration
server:
  servlet:
    context-path: /
springdoc:
  swagger-ui:
    title: API Boilerplate
    version: ${VERSION}
    tagsSorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    path: /docs
    enabled: true
  api-docs:
    path: /docs
    enabled: true
  swagger-config:
    responses:
      error:
        401: "Invalid credentials"
        400: "Problem with the data in the request"
        403: "Request violates some authorization rule"
        404: "Resource requested not found"
        409: "Duplicated Resource"
        422: "Request violates some business rule"
        500: "Some unexpected error has occurred"
        502: "Service is unavailable at the moment"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
